spring:
  jpa:
    database: mysql
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&useSSL=true&verifyServerCertificate=false&characterEncoding=UTF-8
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: blockchain
btc:
  username: 123456
  password: abcdef
  httpAddr: http://123456:abcdef@192.168.0.200:8332
  batchSize: 1
  startBlock: 145651
  endBlock: 586800
ltc:
  username: test
  password: 123456
  httpAddr: http://test:123456@192.168.0.200:9332
  batchSize: 20
  startBlock: 0
  endBlock: 100000
eth:
  httpAddr: http://192.168.0.200:8545
  batchSize: 100
  startBlock: 0
  endBlock: 8200000
tron:
  httpAddr:  http://192.168.0.200:8090 #https://api.trongrid.io
  batchSize: 1000
  startBlock: 0
  endBlock: 1000000
logging:
  level:
    root: info

