spring:
  data:
    mongodb:
      uri: mongodb://server/blockchain

btc:
  username: test
  password: test
  httpAddr: http://server:8332
  batchSize: 2
  startBlock: 0
  endBlock: 596810
ltc:
  username: test
  password: test
  httpAddr: http://server:9332
  batchSize: 20
  startBlock: 0
  endBlock: 1709640
hcash:
  username: test
  password: test
  httpAddr: http://server:14009
  batchSize: 20
  startBlock: 0
  endBlock: 239090
eth:
  httpAddr: http://server:8545
  batchSize: 100
  startBlock: 0
  endBlock: 8200000
tron:
  httpAddr: http://server:8090  #http://47.75.249.4:8090 #http://47.74.242.55:8090 #https://api.trongrid.io #
  batchSize: 1
  startBlock: 0
  endBlock: 11357054
logging:
  level:
    root: info

